# Generated by Django 6.1.1 on 2026-09-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='معرف الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
            ],
            options={
                'verbose_name': 'جلسة محادثة',
                'verbose_name_plural': 'جلسات المحادثة',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف / واتساب')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='اسم الشركة أو النشاط')),
                ('service', models.CharField(blank=True, choices=[('conversational_ai', 'حلول المحادثة الذكية والمساعدين الرقميين'), ('data_analytics', 'تحليل البيانات والأنظمة التنبؤية'), ('custom_ai', 'حلول الذكاء الاصطناعي المخصصة وأتمتة مسارات العمل'), ('general_consultation', 'استشارة عامة في التحول الذكي'), ('other', 'أخرى')], default='general_consultation', max_length=100, verbose_name='الخدمة المطلوبة')),
                ('message', models.TextField(verbose_name='تفاصيل الطلب أو الاستفسار')),
                ('status', models.CharField(choices=[('new', 'طلب جديد'), ('contacted', 'تم التواصل'), ('scheduled', 'تم تحديد موعد استشارة'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='new', max_length=30, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات فريق العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب استشارة / تواصل',
                'verbose_name_plural': 'طلبات الاستشارات والتواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'المساعد Mit'), ('system', 'النظام')], max_length=20, verbose_name='الطرف')),
                ('content', models.TextField(verbose_name='نص الرسالة')),
                ('provider', models.CharField(blank=True, default='', max_length=50, verbose_name='المزود المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثات',
                'ordering': ['created_at'],
            },
        ),
    ]
